<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>comment, text.plain</string>
	<key>name</key>
	<string>Bookmark</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>This is the generic bookmark matcher</string>
			<key>match</key>
			<string>(?&lt;=\#|\/\/)\s*(\!)(.*?)(?=\n)</string>
			<key>name</key>
			<string>comment.bookmark</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\/\*)\s*(\!)</string>
			<key>comment</key>
			<string>For 'PHP', 'CSS', or other languages using /* .. */ for comments</string>
			<key>end</key>
			<string>.(?=\n|\*\/)</string>
			<key>name</key>
			<string>comment.bookmark.php</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\&lt;\!\-\-)\s*(\!)</string>
			<key>end</key>
			<string>.(?=\n|\-\-\&gt;)</string>
			<key>name</key>
			<string>comment.bookmark.html</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.bookmark</string>
	<key>uuid</key>
	<string>8FEAAD72-01E3-4F00-BD4D-A6295C20D2E9</string>
</dict>
</plist>
